const products = [
  {
    id: 1,
    category: "camera",
    image: "https://rukminim2.flixcart.com/image/312/312/xif0q/dslr-camera/g/5/p/eos-18-eos-3000d-canon-original-imahbfq7fjbpzgvm.jpeg?q=70",
    title: "Top Mirrorless...",
    cta: "45,000",
  },
  {
    id: 2,
    category: "headphones",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/k/a/3/-original-imagxaxaxgjzrcfe.jpeg?q=70",
    title: "Best Truewireless...",
    cta: "Grab Now",
  },
  {
    id: 3,
    category: "monitors",
    image: "https://rukminim2.flixcart.com/image/312/312/kxnl6kw0/monitor/r/z/m/vg279qr-full-hd-27-90lm04g0-b02310-asus-original-imaga25uqaxnhk26.jpeg?q=70",
    title: "ASUS Monitors",
    cta: "From ₹14999",
  },
  {
    id: 4,
    category: "smartwatches",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/s/i/u/-original-imah76jt64ffmwg4.jpeg?q=70",
    title: "Noise Smartwatch",
    cta: "From ₹1,099",
  },
  {
    id: 5,
    category: "monitors",
    image: "https://rukminim2.flixcart.com/image/312/312/xif0q/monitor/w/8/u/-original-imahafudnzwzy7hv.jpeg?q=70",
    title: "Dell Monitor",
    cta: "From ₹10,999",
  },
  {
    id: 6,
    category: "shoes",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/i/z/h/-original-imah4syzgvnexbfr.jpeg?q=70",
    title: "Puma Running Shoes",
    cta: "From ₹2,999",
  },
  {
    id: 7,
    category: "headphones",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/v/f/8/-original-imahae3g84uzxbsz.jpeg?q=70",
    title: "boAt Earbuds",
    cta: "Limited Offer!",
  },
  {
    id: 8,
    category: "watches",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/p/5/x/1-nt1805qm01-titan-men-original-imahdujqkjqkapqp.jpeg?q=70",
    title: "Titan Watch",
    cta: "Only ₹1,599",
  },
  {
    id: 9,
    category: "clothing",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/c/i/g/s-os-100-vdorgnl-grn117-veirdo-original-imah4fy3zb5paeaj.jpeg?q=70",
    title: "Men’s T-shirt",
    cta: "Combo Deals",
  },
  {
    id: 10,
    category: "bags",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/rucksack/o/c/y/-original-imagzy3gk6qgxd8w.jpeg?q=70",
    title: "Travel Backpack",
    cta: "From ₹999",
  },
  {
    id: 11,
    category: "camera",
    image: "https://rukminim2.flixcart.com/image/312/312/xif0q/instant-camera/f/4/g/digital-camera-2024-cn8-ic-plus-original-imah235vmnznaygz.jpeg?q=70",
    title: "Top Mirrorless...",
    cta: "3,000",
  }
  ,
  {
    id: 12,
    category: "camera",
    image: "https://rukminim2.flixcart.com/image/312/312/xif0q/dslr-camera/1/9/j/d7500-20-9-d7500-nikon-original-imah3ubrv5y2vynk.jpeg?q=70",
    title: "Top Mirrorless...",
    cta: "67,000",
  }
  ,
  {
    id: 13,
    category: "camera",
    image: "https://rukminim2.flixcart.com/image/312/312/l3hmwsw0/dslr-camera/e/w/n/camera-e-m5-mark-iii-blk-20-om-d-e-m5-mark-iii-blk-olympus-original-imagehphwut7gzje.jpeg?q=70",
    title: "Top Mirrorless...",
    cta: "1,20,000",
  },
  {
    id: 14,
    category: "clothing",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/fabric/o/x/p/no-2-35-m-unstitched-na-7-iwc-premium-fabrics-nilkanth-original-imahbyd6bjhjqsnx.jpeg?q=70",
    title: "Men’s T-shirt",
    cta: "Combo Deals",
  },
  {
    id: 15,
    category: "clothing",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/b/r/m/l-64518810-try-this-original-imah9b23gtxksszv.jpeg?q=70",
    title: "Men’s T-shirt",
    cta: "Combo Deals",
  },
  {
    id: 16,
    category: "clothing",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/a/j/m/xxl-casual-blk-magneto-original-imahc7ggh9a8mfsa.jpeg?q=70",
    title: "Men’s T-shirt",
    cta: "Combo Deals",
  },
  {
    id: 17,
    category: "camera",
    image: "https://rukminim2.flixcart.com/image/312/312/jiyvvrk0/dslr-camera/r/z/w/digital-camera-d7500-d7500-nikon-original-imaf6n7hfevtasgm.jpeg?q=70",
    title: "Top Mirrorless...",
    cta: "1,20,000",
  },
  {
    id: 18,
    category: "camera",
    image: "https://rukminim2.flixcart.com/image/312/312/xif0q/dslr-camera/o/h/6/-original-imah6xmadtujfx9j.jpeg?q=70",
    title: "Top Mirrorless...",
    cta: "1,20,000",
  },
  {
    id: 19,
    category: "camera",
    image: "https://rukminim2.flixcart.com/image/312/312/xif0q/dslr-camera/g/5/p/eos-18-eos-3000d-canon-original-imahbfq7fjbpzgvm.jpeg?q=70",
    title: "Top Mirrorless...",
    cta: "1,20,000",
  },
  {
    id: 20,
    category: "camera",
    image: "https://rukminim2.flixcart.com/image/312/312/l3hmwsw0/dslr-camera/y/z/6/e-m1x-black-body-20-4-em1xinblk-olympus-original-imagehphhnnmqfrg.jpeg?q=70",
    title: "Top Mirrorless...",
    cta: "1,20,000",
  },
  {
    id: 21,
    category: "camera",
    image: "https://rukminim2.flixcart.com/image/312/312/xif0q/role-play-toy/q/b/v/smart-kids-selfie-camera-birthday-gifts-for-hd-digital-video-original-imahfk6yckubqnz2.jpeg?q=70",
    title: "Top Mirrorless...",
    cta: "1,20,000",
  },
  {
    id: 22,
    category: "camera",
    image: "https://rukminim2.flixcart.com/image/312/312/xif0q/dslr-camera/6/i/a/-original-imah6h4qggygqpnw.jpeg?q=70",
    title: "Top Mirrorless...",
    cta: "1,20,000",
  },
  {
    id: 23,
    category: "camera",
    image: "https://rukminim2.flixcart.com/image/312/312/xif0q/dslr-camera/l/i/a/ilce-6100x-24-2-ilce-6100x-sony-original-imah8ptevgtfbssg.jpeg?q=70",
    title: "Top Mirrorless...",
    cta: "1,20,000",
  },
  {
    id: 24,
    category: "camera",
    image: "https://rukminim2.flixcart.com/image/312/312/xif0q/dslr-camera/p/2/k/digital-print-camera-with-instant-photo-printing-capture-original-imahba38psn89pnk.jpeg?q=70",
    title: "Top Mirrorless...",
    cta: "1,20,000",
  },
  {
    id: 25,
    category: "camera",
    image: "https://rukminim2.flixcart.com/image/312/312/xif0q/dslr-camera/o/5/9/autofocus-16x-digital-zoom-rechargeable-camera-48-4k-ultra-hd-original-imahcy7gnjqpdqum.jpeg?q=70",
    title: "Top Mirrorless...",
    cta: "1,20,000",
  },
  {
    id: 26,
    category: "camera",
    image: "https://rukminim2.flixcart.com/image/312/312/xif0q/dslr-camera/m/l/h/kids-toy-gift-mirrorless-camera-mini-20-digital-camera-20mp-original-imahduesd8gmueeg.jpeg?q=70",
    title: "Top Mirrorless...",
    cta: "1,20,000",
  },
  {
    id: 27,
    category: "camera",
    image: "https://rukminim2.flixcart.com/image/312/312/xif0q/dslr-camera/a/k/l/ilce-7rm5-61-ilce-7rm5-sony-original-imagz667ftdz2txn.jpeg?q=70",
    title: "Top Mirrorless...",
    cta: "1,20,000",
  },
  {
    id: 28,
    category: "headphones",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/r/k/p/xo6-gaming-earbuds-with-35ms-low-latency-rgb-led-13mm-drivers-original-imahfayb8x85j7kv.jpeg?q=70",
    title: "Best Truewireless...",
    cta: "Grab Now",
  },
  {
    id: 29,
    category: "headphones",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/5/a/o/-original-imah4fbtayrdgeax.jpeg?q=70",
    title: "Best Truewireless...",
    cta: "Grab Now",
  },
  {
    id: 30,
    category: "headphones",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/t/n/s/-original-imah34yhpbw475hc.jpeg?q=70",
    title: "Best Truewireless...",
    cta: "Grab Now",
  },
  {
    id: 31,
    category: "headphones",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/r/p/t/-original-imagspdrzrf4razp.jpeg?q=70",
    title: "Best Truewireless...",
    cta: "Grab Now",
  },
  {
    id: 32,
    category: "headphones",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/w/d/k/astra-boult-original-imahd2zfafgdggg5.jpeg?q=70",
    title: "Best Truewireless...",
    cta: "Grab Now",
  },
  {
    id: 33,
    category: "headphones",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/d/q/r/-original-imagp6skt77zsdjt.jpeg?q=70",
    title: "Best Truewireless...",
    cta: "Grab Now",
  },
  {
    id: 34,
    category: "headphones",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/h/o/y/super-buds-pro-gt9-number-original-imagz4uwvxn55vsj.jpeg?q=70",
    title: "Best Truewireless...",
    cta: "Grab Now",
  },
  {
    id: 35,
    category: "headphones",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/m/f/e/-original-imah74hcgf6yzgaf.jpeg?q=70",
    title: "Best Truewireless...",
    cta: "Grab Now",
  },
  {
    id: 36,
    category: "headphones",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/o/f/j/navo-buds-z1-number-original-imahcn9sqyp4ffgr.jpeg?q=70",
    title: "Best Truewireless...",
    cta: "Grab Now",
  },
  {
    id: 37,
    category: "headphones",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/9/l/d/-original-imahbzmfpyjpushp.jpeg?q=70",
    title: "Best Truewireless...",
    cta: "Grab Now",
  },
  {
    id: 38,
    category: "monitors",
    image: "https://rukminim2.flixcart.com/image/312/312/xif0q/monitor/i/u/w/-original-imagrkynyhv7vhzd.jpeg?q=70",
    title: "ASUS Monitors",
    cta: "From ₹11999",
  },
  {
    id: 39,
    category: "monitors",
    image: "https://rukminim2.flixcart.com/image/312/312/kq8dua80/monitor/d/e/4/xg32vc-31-5-90lm03s0-b04110-asus-original-imag4agpna9zzjhp.jpeg?q=70",
    title: "ASUS Monitors",
    cta: "From ₹18999",
  },
  {
    id: 40,
    category: "monitors",
    image: "https://rukminim2.flixcart.com/image/312/312/xif0q/monitor/0/e/h/va24ehf-full-hd-23-8-2023-90lm0560-b03110-asus-original-imagrzfdud6str6y.jpeg?q=70",
    title: "ASUS Monitors",
    cta: "From ₹15999",
  },
  {
    id: 41,
    category: "monitors",
    image: "https://rukminim2.flixcart.com/image/312/312/kxnl6kw0/monitor/d/g/t/vz279heg1r-full-hd-27-90lm05t1-b01e10-asus-original-imaga25utdafpent.jpeg?q=70",
    title: "ASUS Monitors",
    cta: "From ₹12999",
  },
  {
    id: 42,
    category: "monitors",
    image: "https://rukminim2.flixcart.com/image/312/312/l4vnbm80/monitor/t/d/y/rog-strix-xg16ahp-w-full-hd-15-6-90lm06id-b02110-asus-original-imagfzk3t8xhs4zf.jpeg?q=70",
    title: "ASUS Monitors",
    cta: "From ₹46999",
  },
  {
    id: 43,
    category: "monitors",
    image: "https://rukminim2.flixcart.com/image/312/312/kx7vc7k0/monitor/c/9/2/pg259qnr-full-hd-24-5-90lm05q3-b01310-asus-original-imag9q5g8n4zdf6h.jpeg?q=70",
    title: "ASUS Monitors",
    cta: "From ₹34999",
  },
  {
    id: 44,
    category: "monitors",
    image: "https://rukminim2.flixcart.com/image/312/312/jzhb24w0/monitor/h/k/a/g-sync-compatible-vg278qr-90lm03p3-b01320-asus-original-imafj5gghzxcnh5z.jpeg?q=70",
    title: "ASUS Monitors",
    cta: "From ₹24999",
  },
  {
    id: 45,
    category: "monitors",
    image: "https://rukminim2.flixcart.com/image/312/312/kl9rssw0/monitor/y/c/2/proart-display-pa278qv-27-pa278qv-asus-original-imagyfpfyzwgdygs.jpeg?q=70",
    title: "ASUS Monitors",
    cta: "From ₹17999",
  },
  {
    id: 46,
    category: "monitors",
    image: "https://rukminim2.flixcart.com/image/312/312/kdnf98w0/monitor/s/a/d/va24ehe-90lm0560-b01110-asus-original-imafug9sftuzdxr8.jpeg?q=70",
    title: "ASUS Monitors",
    cta: "From ₹12999",
  },
  {
    id: 47,
    category: "monitors",
    image: "https://rukminim2.flixcart.com/image/312/312/kdnf98w0/monitor/y/t/f/vg279qm-90lm05h0-b01320-asus-original-imafug9suqantxk2.jpeg?q=70",
    title: "ASUS Monitors",
    cta: "From ₹22999",
  },
  {
    id: 48,
    category: "monitors",
    image: "https://rukminim2.flixcart.com/image/312/312/l55nekw0/monitor/c/b/i/xg16ahp-full-hd-15-6-90lm06i1-b02110-asus-original-imagfwedg55vxhpv.jpeg?q=70",
    title: "ASUS Monitors",
    cta: "From ₹42999",
  },
  {
    id: 49,
    category: "monitors",
    image: "https://rukminim2.flixcart.com/image/312/312/ko8xtow0/monitor/t/a/y/d24-20-66aekac1in-lenovo-original-imag2qwzazcdmqtb.jpeg?q=70",
    title: "ASUS Monitors",
    cta: "From ₹13999",
  },
  {
    id: 50,
    category: "smartwatches",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/o/0/m/-original-imahcvwg57ygwrhm.jpeg?q=70",
    title: "Noise Smartwatch",
    cta: "From ₹2,099",
  },
  {
    id: 51,
    category: "smartwatches",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/e/z/h/-original-imahamwyajf6g3bh.jpeg?q=70",
    title: "Noise Smartwatch",
    cta: "From ₹1,599",
  },
  {
    id: 52,
    category: "smartwatches",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/z/f/6/-original-imah759hrk24uyjw.jpeg?q=70",
    title: "Noise Smartwatch",
    cta: "From ₹3,499",
  },
  {
    id: 53,
    category: "smartwatches",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/y/v/7/-original-imah76jhgpcaktrv.jpeg?q=70",
    title: "Noise Smartwatch",
    cta: "From ₹1,999",
  },
  {
    id: 54,
    category: "smartwatches",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/3/p/w/-original-imahcvwgpsv8hhzp.jpeg?q=70",
    title: "Noise Smartwatch",
    cta: "From ₹3,099",
  },
  {
    id: 55,
    category: "smartwatches",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/b/d/a/-original-imahbzq3xxfkvuhf.jpeg?q=70",
    title: "Noise Smartwatch",
    cta: "From ₹1,799",
  },
  {
    id: 56,
    category: "smartwatches",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/f/b/q/-original-imahcvwfdshwdhsh.jpeg?q=70",
    title: "Noise Smartwatch",
    cta: "From ₹2,499",
  },
  {
    id: 57,
    category: "smartwatches",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/c/t/x/-original-imah6s6prqw3w883.jpeg?q=70",
    title: "Noise Smartwatch",
    cta: "From ₹1,399",
  },
  {
    id: 58,
    category: "smartwatches",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/u/7/x/-original-imahbquz8v7rxfn6.jpeg?q=70",
    title: "Noise Smartwatch",
    cta: "From ₹1,599",
  },
  {
    id: 59,
    category: "smartwatches",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/s/d/o/-original-imagxp8uv5qjsppf.jpeg?q=70",
    title: "Noise Smartwatch",
    cta: "From ₹3,099",
  },
  {
    id: 60,
    category: "smartwatches",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/j/o/i/-original-imah76cawguwqgjc.jpeg?q=70",
    title: "Noise Smartwatch",
    cta: "From ₹1,999",
  },
  {
    id: 61,
    category: "smartwatches",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/d/w/z/-original-imagzw9thgndqgzp.jpeg?q=70",
    title: "Noise Smartwatch",
    cta: "From ₹1,499",
  },
  {
    id: 62,
    category: "shoes",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/w/q/l/7-rso042-7-red-tape-grey-original-imah52c2ad7mbfgt.jpeg?q=70",
    title: "Puma Running Shoes",
    cta: "From ₹2,999",
  },
  {
    id: 63,
    category: "shoes",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/b/c/k/-original-imahan42wemkzsg4.jpeg?q=70",
    title: "Puma Running Shoes",
    cta: "From ₹1,099",
  },
  {
    id: 64,
    category: "shoes",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/d/p/q/6-rso435-6-red-tape-black-original-imahdr573p43uzgv.jpeg?q=70",
    title: "Puma Running Shoes",
    cta: "From ₹2,099",
  },
  {
    id: 65,
    category: "shoes",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/2/y/k/6-rso435-6-red-tape-grey-original-imahdr57qfazbyxp.jpeg?q=70",
    title: "Puma Running Shoes",
    cta: "From ₹1,399",
  },
  {
    id: 66,
    category: "shoes",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/p/l/n/6-mexico-11-6-asian-green-original-imah3nxzfcgrn75k.jpeg?q=70",
    title: "Puma Running Shoes",
    cta: "From ₹1,599",
  },
  {
    id: 67,
    category: "shoes",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/s/p/g/-original-imah6hy3cf38qwrr.jpeg?q=70",
    title: "Puma Running Shoes",
    cta: "From ₹1,799",
  },
  {
    id: 68,
    category: "shoes",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/q/c/h/-original-imahd2p4gr9zsdzs.jpeg?q=70",
    title: "Puma Running Shoes",
    cta: "From ₹2,399",
  },
  {
    id: 69,
    category: "shoes",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/d/v/9/8-5-308237-puma-white-sheen-green-original-imah3h8vepyz3amz.jpeg?q=70",
    title: "Puma Running Shoes",
    cta: "From ₹3,099",
  },
  {
    id: 70,
    category: "shoes",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/f/p/8/-original-imah852zwfgv4bnh.jpeg?q=70",
    title: "Puma Running Shoes",
    cta: "From ₹4,399",
  },
  {
    id: 71,
    category: "shoes",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/o/i/3/-original-imah9mgedyae99av.jpeg?q=70",
    title: "Puma Running Shoes",
    cta: "From ₹1,599",
  },

  {
    id: 72,
    category: "shoes",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/c/r/j/-original-imahddygc7qu9bd4.jpeg?q=70",
    title: "Puma Running Shoes",
    cta: "From ₹2,499",
  },
  {
    id: 73,
    category: "shoes",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/w/h/j/-original-imahe2azgczkjzaf.jpeg?q=70",
    title: "Puma Running Shoes",
    cta: "From ₹2,199",
  },
  {
    id: 74,
    category: "shoes",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/y/k/4/-original-imahfpz5d4rxhxgf.jpeg?q=70",
    title: "Puma Running Shoes",
    cta: "From ₹2,099",
  },
  {
    id: 75,
    category: "watches",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/m/m/t/-original-imahamfxxzzgyf6c.jpeg?q=70",
    title: "Titan Watch",
    cta: "Only ₹1,599",
  },
  {
    id: 76,
    category: "watches",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/b/v/y/-original-imahc78sphhghdw2.jpeg?q=70",
    title: "Titan Watch",
    cta: "Only ₹1,599",
  },
  {
    id: 77,
    category: "watches",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/f/m/l/1-nn1639sm01-titan-men-original-imahdzt2zwnzmjzf.jpeg?q=70",
    title: "Titan Watch",
    cta: "Only ₹1,599",
  },
  {
    id: 78,
    category: "watches",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/j/q/0/1-nn1639sm02-titan-men-original-imahdzt4gpnvh7xz.jpeg?q=70",
    title: "Titan Watch",
    cta: "Only ₹1,599",
  },
  {
    id: 79,
    category: "watches",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/k/t/h/1-1729sl02-titan-men-original-imahdug3m7myxehf.jpeg?q=70",
    title: "Titan Watch",
    cta: "Only ₹1,599",
  },
  {
    id: 80,
    category: "watches",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/q/i/p/1-nt1823qm01-titan-men-original-imahcn4cbez3m3zz.jpeg?q=70",
    title: "Titan Watch",
    cta: "Only ₹1,599",
  },
  {
    id: 81,
    category: "watches",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/j/5/0/-original-imahc6ex7tahhzhz.jpeg?q=70",
    title: "Titan Watch",
    cta: "Only ₹1,599",
  },
  {
    id: 82,
    category: "watches",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/z/h/t/-original-imahcmfzd6whszbe.jpeg?q=70",
    title: "Titan Watch",
    cta: "Only ₹1,599",
  },

  {
    id: 83,
    category: "watches",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/watch/g/y/8/1-nt1802sl11-titan-men-original-imahduj7n6yjhrnz.jpeg?q=70",
    title: "Titan Watch",
    cta: "Only ₹1,599",
  },
  {
    id: 84,
    category: "clothing",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/s/w/5/m-sm-206-peace-smosh-original-imahed48fjwhpjsz.jpeg?q=70",
    title: "Men’s T-shirt",
    cta: "Combo Deals",
  },
  {
    id: 85,
    category: "clothing",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/r/z/u/l-ts-3053-camel-ds-tazo-original-imahdqyvyhbfppgg.jpeg?q=70",
    title: "Men’s T-shirt",
    cta: "Combo Deals",
  },
  {
    id: 86,
    category: "clothing",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/k/s/2/xxl-p747-technosport-original-imah45hxhkpc3w7j.jpeg?q=70",
    title: "Men’s T-shirt",
    cta: "Combo Deals",
  },
  {
    id: 87,
    category: "clothing",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/z/v/n/-original-imagy2ms3qczg2qm.jpeg?q=70",
    title: "Men’s T-shirt",
    cta: "Combo Deals",
  },
  {
    id: 88,
    category: "clothing",
    image: "https://rukminim2.flixcart.com/image/612/612/l4vnbm80/t-shirt/i/j/q/m-askporgfj72665-new-allen-solly-original-imagfzk8vjxgurcj.jpeg?q=70",
    title: "Men’s T-shirt",
    cta: "Combo Deals",
  },
  {
    id: 89,
    category: "clothing",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/d/o/c/xxl-314-black-scatchite-original-imahcb38e6ryynmy.jpeg?q=70",
    title: "Men’s T-shirt",
    cta: "Combo Deals",
  },
  {
    id: 90,
    category: "clothing",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/d/y/k/m-or13new-technosport-original-imah5gcdgkapdf5n.jpeg?q=70",
    title: "Men’s T-shirt",
    cta: "Combo Deals",
  },
  {
    id: 91,
    category: "clothing",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/s/x/a/m-auskk01268-ausk-original-imah9u89fhastsyp.jpeg?q=70",
    title: "Men’s T-shirt",
    cta: "Combo Deals",
  },
  {
    id: 92,
    category: "clothing",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/f/h/c/xxl-vm-1449022-14472-2-v-mart-original-imah8u9rednqcs3h.jpeg?q=70",
    title: "Men’s T-shirt",
    cta: "Combo Deals",
  },
  {
    id: 93,
    category: "bags",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/backpack/g/l/h/-original-imahdq23r9cxkyvs.jpeg?q=70",
    title: "Travel Backpack",
    cta: "From ₹999",
  },
  {
    id: 94,
    category: "bags",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/backpack/4/m/b/-original-imahd2pargh64zcy.jpeg?q=70",
    title: "Travel Backpack",
    cta: "From ₹999",
  },
  {
    id: 95,
    category: "bags",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/rucksack/l/d/q/80-litres-curve-water-resistant-rucksack-for-hiking-trekking-and-original-imah8kx4w6fatpqg.jpeg?q=70",
    title: "Travel Backpack",
    cta: "From ₹999",
  },
  {
    id: 96,
    category: "bags",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/backpack/l/v/5/14-2-pulse-backpack-for-men-women-3-compartment-casual-rain-original-imahdvnmadf5zvsz.jpeg?q=70",
    title: "Travel Backpack",
    cta: "From ₹999",
  },
  {
    id: 97,
    category: "bags",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/backpack/u/v/2/12-5984251968504-cosmic-backpack-e-light-blue-7-08661417322835-original-imahfqsjtpvdjkm2.jpeg?q=70",
    title: "Travel Backpack",
    cta: "From ₹999",
  },
  {
    id: 98,
    category: "bags",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/sling-bag/4/r/i/cross-body-men-s-sling-bag-for-travel-business-offices-cash-original-imahb5urfm6hytzh.jpeg?q=70",
    title: "Travel Backpack",
    cta: "From ₹999",
  },
  {
    id: 99,
    category: "bags",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/sling-bag/6/u/w/premium-kangaroo-embossed-logo-men-leather-sling-shoulder-bag-original-imah7z6ga9phnfgp.jpeg?q=70",
    title: "Travel Backpack",
    cta: "From ₹999",
  },
  {
    id: 100,
    category: "bags",
    image: "https://rukminim2.flixcart.com/image/612/612/xif0q/backpack/k/k/b/18-bag-for-men-women-office-college-school-12-221-backpack-original-imah9nz3rqua4gey.jpeg?q=70",
    title: "Travel Backpack",
    cta: "From ₹999",
  },


];

export default products;